### ISSUE TITLE
Windows cannot find './dotnet/Style2Paint.exe'.

### ISSUE THREAD

**Issue by GoldenMaximo** [lllyasviel/style2paints#147]
Hi,

I downloaded [Style2Paints V4.5](https://drive.google.com/open?id=1gmg2wwNIp4qMzxqP12SbcmVAHsLt1iRE
), uzipped it then I tried to execute the style2paints.exe file on the root folder.

I chose the first option of the GPU prompt:
![1](https://user-images.githubusercontent.com/51284438/90327260-16c7b100-df68-11ea-9815-1799f8731bc6.png)

Then I was prompted with the following error:
![2](https://user-images.githubusercontent.com/51284438/90327283-60180080-df68-11ea-840f-50f2e34e9614.png)
I'm not sure if that's the file the application is looking for but at the open explorer window at the right side of the image the .exe seems to exist within the assets/dotnet folder.

Upon clicking "OK" on the error prompt the "Now Loading..." window closes and the terminal proceeds to do the following:
![3](https://user-images.githubusercontent.com/51284438/90327334-17ad1280-df69-11ea-922d-56a44bdf60c9.png)

I've tried to run a simple `GET /` on the port the server is listening but it returns 404
![Screenshot_2](https://user-images.githubusercontent.com/51284438/90327345-41fed000-df69-11ea-870f-30142fbc87ee.png)

My setup:
CPU: AMD Ryzen 5 3600
GPU: AMD Radeon RX 5700 XT (Driver ver. 20.8.1 (Up-to-date))

My OS is 64-bit.
I have .NET Framework 4.8 installed.
I've tried running the .exe as administrator but the same issue occurs.

[syslog.txt](https://github.com/lllyasviel/style2paints/files/5080055/syslog.txt)

If I'm doing something wrong please let me know. Thanks in advance.

**Comment by lllyasviel** [comment]
You may keep the console window open and manually run the 'assets/dotnet/Style2Paint.exe' and see what will happen. It is very wired... maybe the main exe is not running in a correct path.

**Comment by GoldenMaximo** [comment]
@lllyasviel it worked. Thank you.

I found out that the application is quite slow using only the CPU but it works nonetheless.
Wish I knew OpenCL or Vulkan so I could contribute to the project on the AMD side.

The issue was resolved through the manual workaround you suggested but it's not fixed as I still get the original error when running the main exe. For that reason I'll leave the issue open but feel free to close it if you feel this is not worth bothering with.

**Comment by gceboh** [comment]
Current workaround for AMD GPU users, which may be helpful:
[[Performance Tuning] Workarounds for Integrated Graphics/AMD GPU Users](https://github.com/lllyasviel/style2paints/issues/146)

**Comment by gceboh** [comment]
Thanks for lllyasviel's workaround.

It's a very difficult bug, which I had considered for a long time.

**Recently, I got hint from this post: [Difference between “%~dp0” and “.\”?](https://stackoverflow.com/questions/15890856/difference-between-dp0-and/15891127)**

---

Please pay attention to the path mentioned in the error message:
![bug](https://user-images.githubusercontent.com/51284438/90327283-60180080-df68-11ea-840f-50f2e34e9614.png)

The path mentioned in the error message: 
`./dotnet/Style2Paints.exe`


## Reproduce
It's hard to reproduce this bug because of complex system configuration/security mechanism.(E.g., NTFS Permissions of the system drive, Group Policy of the windows system. )

But the following simple example can reproduce it.

1. Create a batch file named "test.bat" with the following content, and place it in the same dir of "assets\style2paintsv45.exe".

```
start .\dotnet\Style2Paints.exe
pause
```

2. Run this batch file by double click it, and the browser is launched without any error.

3. Now, **run it As Administrator** from right click context menu, and the following error will appear:
```
Windows cannot find '.\dotnet\Style2Paints.exe',Make sure you typed the name correctly, and then try again.
```

## Fix
change batch file content to:
```
start %~dp0dotnet\Style2Paints.exe
pause
```
(do not add a Backslash after "%~dp0")

---

Hope the above info could help the debugging process, and developers who meet with similar problems.
