### ISSUE TITLE
Use Intergrated graphics card only

### ISSUE THREAD

**Issue by Neutrino0532** [lllyasviel/style2paints#159]
I'm using AMD R7-4800H and RTX2060, but the application runs on Radeon graphics cards only rather than
 2060. 
I've set the executable to use High-proformance graphics card via NVIDIA control panel, but it seems doesn't work.
application version V4.5, 
system: windows10 2004
Graphics card driver: Geforce Game 461.72

Thanks for supporting

**Comment by gceboh** [comment]
The following workaround may work for NVIDIA Graphic cards which are imcompatibale or not listed in the support list, including NVIDIA Gefore MX series.
**However, sorry that I can't test the method, due to lack of specific hardware.**

# Workaround

1.Install: NVIDIA CUDA 8 ([Link](https://developer.nvidia.com/cuda-80-ga2-download-archive))
(Using CUDA version 8 due to TensorFlow 1.4.0 is integrated in Style2Paints V4.5)

Install "Base Installer" and "Patch 2".


2.Install:  NVIDIA cuDNN v6.0 (April 27, 2017), for CUDA 8.0 ([Link](https://developer.nvidia.com/rdp/cudnn-archive#a-collapse51b))

For Win 10:[Link](https://developer.nvidia.com/compute/machine-learning/cudnn/secure/v6/prod/8.0_20170427/cudnn-8.0-windows10-x64-v6.0-zip)
Rigister a account is needed before downloading.
For installation of cuDNN, you may need some tutorials.


3.Search in Style2Paints V4.5's folder with the keyword `nvidia` (Make sure "Search Through File Contents" is checked.) Delete all the found `*.dll` files.
