### ISSUE TITLE
No Source Code for V4

### ISSUE THREAD

**Issue by EuphoricPenguin** [lllyasviel/style2paints#166]
I have something of a bone to pick with the maintainers of this repository. First, you create a project under the guise that it will remain free and open source. Second, you slowly develop the project until (at some point) you decide to turn your GitHub into a poor excuse for a landing page? You're not using the releases section to distribute your binaries; instead, you resort to a sketchy personal Google Drive. On top of this, you fail to make clear the distinction between the license (which allows commercial use) and your README (which has ambiguous language that effectively corrupts the original license and makes an entirely new one). Not only all of this, but you fail to even include the **source code** for your recent development? It's hardly *open* source when there isn't any source to be found. What is the function of your license when we can't even peek behind the curtain? I'd seriously re-consider the direction you're taking this project if you really want to convince people who are actually interested in true FOSS development that your project is worth their time. Otherwise, I kindly ask you to consider leaving GitHub, as this clearly has no place among projects that complete the bare minimum requirement of releasing **source code**.

**Comment by marcussacana** [comment]
no one give a fck

**Comment by EuphoricPenguin** [comment]
> no one give a fck
That's the problem. I think the irony of explaining why open source matters in a thread on GitHub is enough to prove my point.

**Comment by lllyasviel** [comment]
Hi Penguin,


We will release the source codes for the previous online version style2paints v4 and this offline version style2paints v4.5 when the project SEPA (previously called style2paints v5) is released, at which point the life cycle of style2paints 4.X is end.


The currently available source code of style2paints v3 is released under Apache 2.0 lisence. Apart from source codes, note that the pretrained models are standalone materials and we preserve all rights of these model files.&nbsp;


Finally, the binary releases are too big for github release pages, which may cause network traffic banning.&nbsp;


Thank you for your attention and suggestions.


Best,
Zhang



---Original---
From: ***@***.***&gt;
Date: Mon, May 24, 2021 08:44 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [lllyasviel/style2paints] No Source Code for V4 (#166)




 
I have something of a bone to pick with the maintainers of this repository. First, you create a project under the guise that it will remain free and open source. Second, you slowly develop the project until (at some point) you decide to turn your GitHub into a poor excuse for a landing page? You're not using the releases section to distribute your binaries; instead, you resort to a sketchy personal Google Drive. On top of this, you fail to make clear the distinction between the license (which allows commercial use) and your README (which has ambiguous language that effectively corrupts the original license and makes an entirely new one). Not only all of this, but you fail to even include the source code for your recent development? It's hardly open source when there isn't any source to be found. What is the function of your license when we can't even peek behind the curtain? I'd seriously re-consider the direction you're taking this project if you really want to convince people who are actually interested in true FOSS development that your project is worth their time. Otherwise, I kindly ask you to consider leaving GitHub, as this clearly has no place among projects that complete the bare minimum requirement of releasing source code.
