### ISSUE TITLE
Lambda value & training

### ISSUE THREAD

**Issue by znxlwm** [lllyasviel/style2paints#19]
Hello, this repository is so cool!! thank you for your effort.

I have two questions,

1) In the paper, you specify for alpha and beta values as 0.3 and 0.9.

However, you did not refer to lambda value in Eq 5.

![image](https://user-images.githubusercontent.com/7044742/30952058-130eb15c-a461-11e7-9e62-3a9618e4a502.png)

What did you use lambda value?

2) Your L1 loss consists of three equations as below. 

![image](https://user-images.githubusercontent.com/7044742/30952452-e38313f4-a462-11e7-8093-b3a8d68d4119.png)

How to train generator, guide decoder 1 and 2 ??

I think that generator, guide decoder 1 and 2 weights are updated independently by using the loss from each network.

i.e, ![image](https://user-images.githubusercontent.com/7044742/30952734-fc8816e6-a463-11e7-8f8f-1dedf32e1a3e.png) is used to update generator, 
![image](https://user-images.githubusercontent.com/7044742/30952973-055a1a66-a465-11e7-9435-365da7931bc1.png) is used to update guide decoder 1 (include from first to mid-level layers of generator), and 
![image](https://user-images.githubusercontent.com/7044742/30953025-2f066c0c-a465-11e7-8c06-cf94c98a5a2d.png) is used to update guide decoder 2 (include from first to mid-level layers of generator). 
This is right??

However, in the paper, I understand that sum of all l1 loss (the results of Eq 1) is used to update only the generator, or the generator and the guide decoder 1 and 2.

It is very confusing.

**Comment by lllyasviel** [comment]
Oh this paper is a baby version of this project, written 4 months ago, and it is not highly related to methods in this repo. But I will try my best to answer your questions.
One important thing is that there are a critical mistake in the paper. The V(x) should be V(y) and the fixed formular should be:
![image](https://user-images.githubusercontent.com/19834515/30956646-8e141186-a46a-11e7-9555-d16f13f11b74.png)
I have fixed the mistake in IEEE version but I forgot to update it in arxiv.
OK. Let me anwser your questions.

1. the lambda value is 0.01. I did not mention the value because there are lots of similar papers based on a combination of l1 loss and cGAN loss and the lambda is always 0.01 in nearly all of their codes. In fact these papers shares a same formula, including famous pix2pix. Some conferences limits their papers to 6 pages, and we have to cut some not important things.
*But nowadays after the dense CNN or resBlocks are proposed, the lambda should be 1 or 0.1 if you use a very deep and stacked discriminator.*
*It is another story if you use GP. Maybe you can give up the lambda if you resort to a GP solution.*

2. Yes, you are right. We train these 3 gradients all together. In TF, reseachers can combine many losses from different layers easily. The guide decoders are parts of generators and our G combines of Gf,  Gg1 and Gg2. Gf and Gg1 share low-level weights, and Gf, Gg1, Gg2 share low-level and mid-level weights. The three G outputs receives l1 gradients accrodingly from the loss mentioned above. Only Gf receives adv losses. Only Gf has skip-connections to low-level encoder layers.

hmm maybe we should have a new paper.

**Comment by znxlwm** [comment]
Thanks for your reply, but I have still in confusing for answer 2.


- update optimizer( (Gf.param, Gg1.param, Gg2.param) ) by ![image](https://user-images.githubusercontent.com/7044742/30959125-329016ec-a47a-11e7-890e-cc1a17324a3f.png)

or

- update optimizer(Gg1.param) by ![image](https://user-images.githubusercontent.com/7044742/30959064-097f40c0-a47a-11e7-90e3-110260214ccd.png)
- update optimizer(Gg2.param) by ![image](https://user-images.githubusercontent.com/7044742/30959088-16325708-a47a-11e7-9962-dee2659ed803.png)
- update optimizer(Gf.param) by ![image](https://user-images.githubusercontent.com/7044742/30959020-e7279ff4-a479-11e7-8e01-6953681c5c68.png)

What is correct?

**Comment by lllyasviel** [comment]
Adam optimizer for combined loss.

**Comment by znxlwm** [comment]
Thank you!!

I try it!
