### ISSUE TITLE
What do `k_resize`, `d_resize`, `s_resize`, and `m_resize` do? 

### ISSUE THREAD

**Issue by geekman2** [lllyasviel/style2paints#45]
I'm trying to go through the code, but I can't figure out what these functions do.  Obviously they perform resizing based on some parameter, but it's not clear what. So far as I've been able to tell
k_resize: Resize based on k, a semi-arbitrary value
m_resize: Resize to the minimum value of <something>
s_resize: Resize parameter A to the shape of parameter B
d_resize: No clue

**Comment by lllyasviel** [comment]
k_resize(resize with kernel size of nn):
find a suitable size for nn to resize, the kernel of nn is k
m_resize(resize in order to change the minimum value of image shape):
the minimum value of image shape will be m after resize
s_resize(resize in order to tune the ratio of shape):
the image will have same ratio to s after resize
d_resize(resize directly):
resize image directly to shape d

all these resize performs area when squeezing and lanczos when expanding.
